name: Build Android APK and Deploy to Google Drive
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Install test types
      run: npm install -D @types/jest
      
    - name: Build web app
      run: npm run build
    
    - name: Add Android platform
      run: npx cap add android
    
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Build Android APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug --no-daemon --parallel
    
    - name: Generate APK filename with timestamp
      id: apk-filename
      run: |
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        echo "APK_FILENAME=miapp-galeria-${TIMESTAMP}-${GITHUB_SHA::7}.apk" >> $GITHUB_ENV
    
    - name: Locate and rename APK
      run: |
        cp android/app/build/outputs/apk/debug/app-debug.apk ./${{ env.APK_FILENAME }}
      
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: ./${{ env.APK_FILENAME }}
        retention-days: 14
      
    - name: Upload APK to Google Drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        filename: ${{ env.APK_FILENAME }}
        folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        name: ${{ env.APK_FILENAME }}
        mimeType: "application/vnd.android.package-archive"
        overwrite: false
        
    - name: Cleanup
      if: always()
      run: rm -f credentials.json ${{ env.APK_FILENAME }}

